### ISSUE TITLE
build_wheel.sh: TEST_COMMAND is only used if PYTHON_IMPORT_NAME is set to empty string.

### ISSUE THREAD

**Issue by ostueker** [ComputeCanada/wheels_builder#13]
If I understand the implementation of the testing in `build_wheel.sh` correctly,
setting `TEST_COMMAND` will only have an effect if `PYTHON_IMPORT_NAME` is actively set to an empty string:

```bash
	if [[ -n "$PYTHON_IMPORT_NAME" ]]; then
		test_import "$PYTHON_IMPORT_NAME" "$PYTHON_TESTS"
	elif [[ -n "$TEST_COMMAND" ]]; then
		$TEST_COMMAND
	fi
```
Remember: by default the value of `PYTHON_IMPORT_NAME` is set to `$PACKAGE`.
So unless it is set to an empty string (or unset) this if-clause has a chance to reach to executing `TEST_COMMAND`.

**Comment by mboisson** [comment]
Fixed
