### ISSUE TITLE
build_wheel deps with hyphen

### ISSUE THREAD

**Issue by lemairecarl** [ComputeCanada/wheels_builder#19]
If the dependency that was download is `Pillow-SIMD-7.0.0.post3.tar.gz`, the script tries to build just `Pillow` instead of `Pillow-SIMD`. The script assumes that there are no hypens in the package name:

https://github.com/ComputeCanada/wheels_builder/blob/d56ea31f17be0776bf3aef5e3b3055a29a60acd2/build_wheel.sh#L182

Insteaf of taking the first hypen-separated token, could we remove from the right? Not sure if we can count on a fixed number of tokens...

**Comment by ccoulombe** [comment]
Indeed, good catch! File names...a regex will be better suited here

**Comment by ccoulombe** [comment]
`grep -Po '^[\w-_]+-' | sed 's/.$//'` should do the trick. It will handle anything [`a-z`, `A-Z`, `-`, `_`] at the start of line until `-`. sed will substitute by nothing the last character of every line.

**Comment by ccoulombe** [comment]
Fixed in e87dad8d884c738bbb1d8b6dbb7b5c0128a19eaf
