### ISSUE TITLE
wheel_architecture / cp_wheels do not handle some wheels

### ISSUE THREAD

**Issue by lemairecarl** [ComputeCanada/wheels_builder#22]
I have unmanylinuxized a wheel, and when trying to use `cp_wheels`, I get:

```
Error, wheel with unknown compatibility layer encountered. torchvision-0.8.1-cp36-cp36m-linux_x86_64.whl, unknown, generic
```

To investigate, Maxime has suggested to run `wheel_architecture`. Here is the output:

```
$ wheel_architecture.sh torchvision-0.8.2-cp38-cp38-linux_x86_64.whl 
ldd: warning: you do not have execution permission for `./torchvision.libs/libpng16.7f72a3c5.so.16'
ldd: warning: you do not have execution permission for `./torchvision.libs/libpng16.7f72a3c5.so.16'
ldd: warning: you do not have execution permission for `./torchvision.libs/libjpeg.ceea7512.so.62'
ldd: warning: you do not have execution permission for `./torchvision.libs/libjpeg.ceea7512.so.62'
ldd: warning: you do not have execution permission for `./torchvision.libs/libcudart.459720b2.so.10.2'
ldd: warning: you do not have execution permission for `./torchvision.libs/libcudart.459720b2.so.10.2'
ldd: warning: you do not have execution permission for `./torchvision.libs/libz.1328edc3.so.1'
ldd: warning: you do not have execution permission for `./torchvision.libs/libz.1328edc3.so.1'
ldd: warning: you do not have execution permission for `./torchvision/image.so'
        libc10.so => not found
        libtorch.so => not found
        libtorch_cpu.so => not found
        libtorch_python.so => not found
        libc10_cuda.so => not found
        libtorch_cuda.so => not found
ldd: warning: you do not have execution permission for `./torchvision/image.so'
        libc10.so => not found
        libtorch.so => not found
        libtorch_cpu.so => not found
        libtorch_python.so => not found
        libc10_cuda.so => not found
        libtorch_cuda.so => not found
./torchvision/image.so is missing some libraries in Nix
./torchvision/image.so is missing some libraries in Gentoo
ldd: warning: you do not have execution permission for `./torchvision/_C.so'
        libc10.so => not found
        libtorch.so => not found
        libtorch_cpu.so => not found
        libtorch_python.so => not found
        libcudart.so.10.2 => not found
        libc10_cuda.so => not found
        libtorch_cuda.so => not found
ldd: warning: you do not have execution permission for `./torchvision/_C.so'
        libc10.so => not found
        libtorch.so => not found
        libtorch_cpu.so => not found
        libtorch_python.so => not found
        libcudart.so.10.2 => not found
        libc10_cuda.so => not found
        libtorch_cuda.so => not found
./torchvision/_C.so is missing some libraries in Nix
./torchvision/_C.so is missing some libraries in Gentoo
unknown generic
```

(The warnings are also there when unmanylinuxizing. Related to this closed PR: https://github.com/ComputeCanada/easybuild-computecanada-config/pull/7)

However, the wheel has been confirmed to work. It's unclear what the fix would be in this situation. As a workaround, I just copied the wheels manually.

As a side note, I tried building the wheel, but it's prevented by the build script, since it checks for the presence of a CUDA GPU while building, to get the model, driver version, or something. Since we build on `build-node`, this is bad.

**Comment by mboisson** [comment]
@ppomorsk also encountered a similar issue. 

There are a few options, but none is perfect. 

1) We could check whether these .so are contained within the wheel, and if they are, assume that they can find eachother (which is likely, but not guaranteed)
2) We could provide an override flag (but then, the person who runs the cp_wheels.sh script needs to provide the correct architecture)
3) We could patch the wheel by adding $ORIGIN to the runpath and hope that this fixes the errors first. 
...

**Comment by ppomorsk** [comment]
Let me just mention that my workaround was to download the wheel and unpack it, then point LD_LIBRARY_PATH to the missing libraries inside the wheel so that they can be found.

After this cp_wheels worked without issue.

**Comment by lemairecarl** [comment]
@mboisson this seems like a lot of work, when just copying the wheels manually work fine. Since it's only for some exceptional cases, I would just do that.

**Comment by mboisson** [comment]
Closing as there is no obvious solution.
