### ISSUE TITLE
manipulate_wheels.py changing permissions inside of wheels

### ISSUE THREAD

**Issue by lucasn42** [ComputeCanada/wheels_builder#42]
Applying <code>manipulate_wheels.py</code> to a wheel containing executable binaries seems to have a side-effect of changing these files' permissions. Example:

### Wheel before manipulation

```
$ ll ray-1.8.0.data/purelib/ray/core/src/ray/thirdparty/redis/src/
total 11240
-r-xr-xr-x 1 lucasn1 lucasn1 11509224 Nov 25 18:27 redis-server
```

### Wheel post manipulation:

```
$ ll ray-1.8.0+computecanada.data/purelib/ray/core/src/ray/thirdparty/redis/src/
total 11240
-rw------- 1 lucasn1 lucasn1 11509224 Nov 25 20:00 redis-server
```

Manipulation command was:

<code>manipulate_wheels.py -i -w ray-1.8.0-cp38-cp38-linux_x86_64.whl</code>

To reproduce on build-node, use <code>/tmp/ray-1.8.0-cp38-cp38-linux_x86_64.whl</code>

**Comment by ccoulombe** [comment]
The users have to chmod the binaries in order to get Ray working.

**Comment by mboisson** [comment]
To be investigated, but in the mean time, the wheels can be fixed manually, simply unzip the wheel, change the permissions and zip it back.

**Comment by ccoulombe** [comment]
Related? 
https://bugs.python.org/issue15795

**Comment by ccoulombe** [comment]
The wheels have been manually fixed and synced.
```
ray-1.8.0+computecanada-cp38-cp38-linux_x86_64.whl
ray-1.8.0+computecanada-cp39-cp39-linux_x86_64.whl

```

**Comment by mboisson** [comment]
They were not really fully patched.

**Comment by mboisson** [comment]
This is now fixed on our build-node. 

Pull request has been opened upstream for wheelfile. 

https://github.com/MrMino/wheelfile/pull/18
