### ISSUE TITLE
For packages that contains "." this wheel builder changes "." to "-"

### ISSUE THREAD

**Issue by aroudgar** [ComputeCanada/wheels_builder#57]
For python packages that contain "." in their name, e.g. ruamel.yaml this wheels_builder changes the name of the package from   ruamel.yaml  to ruamel-yaml  This is because the "wheelfile" package that insert "+computecanada" to the wheel changes "*.dist-info" file within the wheel from  ruamel.yaml-0.17.16.dist-info  to ruamel_yaml-0.17.16+computecanada.dist-info, note: "." changes to "_". This will change the name of the package from ruamel.yaml to ruamel-yaml in "pip list" command and also cause error for softwares that requires this package. 

Example:
I already made ruamel.yaml-0.17.16+computecanada-py3-none-any.whl using this package builder:
```
$ virtualenv ENV
$ . ENV/bin/activate
$ pip install ruamel.yaml-0.17.16+computecanada-py3-none-any.whl
$ pip list 
Package          Version              
---------------- ---------------------
pip              20.0.2               
ruamel-yaml      0.17.16+computecanada
ruamel-yaml-clib 0.2.6+computecanada  
setuptools       46.1.3               
wheel            0.34.2               
```

because of 
ENV/lib/python3.8/site-packages/ruamel_yaml-0.17.16+computecanada.dist-info
If I rename it to "ruamel.yaml-0.17.16+computecanada.dist-info" everything looks good

My conclusion: there might be a tiny bug in  "wheelfile.py" ("wheelfile" package)

**Comment by mboisson** [comment]
Unsure if the issue is in https://github.com/ComputeCanada/wheels_builder/blob/main/manipulate_wheels.py or in `wheelfile`

**Comment by mboisson** [comment]
I think that actually comes from the fact that `wheelfile` uses `canonicalize_name`
https://github.com/MrMino/wheelfile/blob/master/wheelfile.py#L1798
from `packaging.utils`:
https://packaging.pypa.io/en/latest/utils.html


are dots in python package names actually valid ?

**Comment by mboisson** [comment]
Is it actually a problem that it renames the `distinfo` ? i.e. does it prevent dependency resolution for some packages ?

**Comment by aroudgar** [comment]
Yes, "cwltool" is another python package that needs this package and it checks to see if it exists at runtime using pkg_resources, e.g., you can run "cwltool"  and since it cannot find "ruamel.yaml" dist-info  it though an error. I can rename ".dist-info" file of  ruamel.yaml and  ruamel.yaml.clib and fix the problem but I thought maybe I should report it.

**Comment by mboisson** [comment]
@aroudgar please try again. This should be fixed now.

**Comment by aroudgar** [comment]
Yes, it is fixed. Thank you!
