### ISSUE TITLE
manipulate_wheels breaks numpy requirements

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/wheels_builder#73]
Base requirement `numpy<1.26.0,>=1.18.5` became `numpy (>=1.21)<1.26.0,>=1.18.5` when the numpy version was adjusted.

The wheel then fails to install as packaging fails to correctly parse the requirement.

**Comment by mboisson** [comment]
Which package is that ?

**Comment by mboisson** [comment]
By the way, that package requirement is already broken, `<1.26.0` makes no sense as the latest version of numpy is `1.23.x`, 1.26 is way down the line and nobody knows what will happen by then.

**Comment by ccoulombe** [comment]
`scipy`. This happens when adjusting numpy requirement to a minimal version, when there's already a range.
And they are following: https://numpy.org/doc/stable/user/depending_on_numpy.html#runtime-dependency-version-ranges

> That said, if you are (a) a project that is guaranteed to release frequently, (b) use a large part of NumPy’s API surface, and (c) is worried that changes in NumPy may break your code, you can set an upper bound of <MAJOR.MINOR + N with N no less than 3, and MAJOR.MINOR being the current release of NumPy [*](https://numpy.org/doc/stable/user/depending_on_numpy.html#id3). If you use the NumPy C API (directly or via Cython), you can also pin the current major version to prevent ABI breakage. Note that setting an upper bound on NumPy may [affect the ability of your library to be installed alongside other, newer packages](https://iscinumpy.dev/post/bound-version-constraints/).

> [*](https://numpy.org/doc/stable/user/depending_on_numpy.html#id2)
The reason for setting N=3 is that NumPy will, on the rare occasion where it makes breaking changes, raise warnings for at least two releases. (NumPy releases about once every six months, so this translates to a window of at least a year; hence the subsequent requirement that your project releases at least on that cadence.)

**Comment by mboisson** [comment]
I see. I guess we'll have to adjust the logic for when there are complicated version schemes like that

**Comment by ccoulombe** [comment]
Yes, with the different permutations possible.
