### ISSUE TITLE
build_wheel.sh: misleading output

### ISSUE THREAD

**Issue by cwant** [ComputeCanada/wheels_builder#76]
Hi all, just building a wheel after not doing so for some time.
The output here does not reference `manipute_wheel.py` or `cp_wheels.sh`:

https://github.com/ComputeCanada/wheels_builder/blob/aa5ceb7b1131a609e5c91195c5bfd8bf5b8fd8e7/build_wheel.sh#L580

I wonder if this is obsolete?

**Comment by cwant** [comment]
Okay, a bit of a surprise, I think this does the `manipulate_wheel.py` for me (I think? The "Builidng Wheels" documentation page says I have to run it ...?).
I ran into some surprises because I started my build on the `master` branch, not knowing that `main` is the one that matters now.

**Comment by ostueker** [comment]
`build_wheel.sh` will run `manipulate_wheel.py` to add the +computecanada version tag and also use a slightly older, yet still supported version of numpy to avoid locking the wheel to the just released version of numpy to which some packages are not yet compatible.

**Comment by ccoulombe** [comment]
It is not obsolete, as you still need to sync the wheel, either manually or by using `cp_wheels`.
But yeah, using the `main` branch will give you the latest features and configuration.

**Comment by ccoulombe** [comment]
Closing as no further input since. Feel free to re-open if needed.
